name: debatemate

services:
  coturn:
    image: coturn/coturn:latest
    container_name: coyouturnme
    restart: unless-stopped
    # network_mode: host
    ports:
      ## STUN/TURN
      - '3478:3478'
      - '3478:3478/udp'
      # - "3479:3479"
      # - "3479:3479/udp"
      # - "80:80"
      # - "80:80/udp"
      ## STUN/TURN SSL
      - '5349:5349'
      - '5349:5349/udp'
      # - "5350:5350"
      # - "5350:5350/udp"
      # - "443:443"
      # - "443:443/udp"
    volumes:
      - ../turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ./signal/cert:/etc/coturn/cert
    command:
      # turnserver
      # -n
      # --log-file=stdout
    #   --min-port=49160
    #   --max-port=49200
    #   --no-cli
    #   --no-tcp
    #   --listening-port=3478
    #   --tls-listening-port=5349
    #   --alt-listening-port=0
    #   --alt-tls-listening-port=0
    #   -u someUser:somePassword
    #   --realm=turn.example.com
    #   --no-dtls
    #   --no-tlsv1
    #   --no-tlsv1_1
  signal:
    build:
      context: ./signal
      dockerfile: Dockerfile
    container_name: signalm8
    depends_on:
      - coturn
    ports:
      - '5000:5000'
